= Microshell

== Main

[plantuml, target=main, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

note left
  int main(int argc, char *argv[], char *env[]);
end note
start
:Increase of 1 argv;
:microshell;
stop

@enduml
....

=== Microshell

[plantuml, target=microshell, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

note left
  int microshell(char *argv[], char *env[]);
end note
start

while (*argv != 0?) is (has argument(s))
  :find the command;
  :init pipe;
  if (is a cd command) then (yes)
    :change directory;
  else (no)
    :execute the command;
  endif
endwhile (No more argument)

:return 0;;
stop

@enduml
....

=== Find the command

[plantuml, target=find-the-command, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

start

while ((*argv)[index] != 0\nAND (*argv)[index] != ";"\nAND (*argv)[index] != "|") is (has argument(s))
  :index++;;
endwhile
if ((*argv)[index]) then (is equal NULL)
  :*arguments = &((*arguments)[index]);;
  :return;;
  stop
endif

if ((*argv)[index]) then (is equal\n"|")
  :isPipe = 1;;
else (is not equal "|")
endif

:(*arguments)[index] = 0;;
:*arguments = &((*arguments)[index + 1]);;

stop

@enduml
....

=== Pipe

[plantuml, target=pipe, format=svg, width=100%]
....
@startuml
skinparam defaultFontName JetBrains Mono

start

:Init a pipe;
:pid = fork();;
fork
note left
  if pid != 0
  Parent process
end note
  if (is pipe ?) then (yes)
    :dup2(pipe[0], 0);;
    :close(pipe[0]);;
    :close(pipe[1]);;
  else (no)
  endif
  :waitpid(pid, 0, 0);;
fork again
note left
  if pid == 0
  Child process
end note
  if (is pipe ?) then (yes)
    :dup2(pipe[1], 1);;
    :close(pipe[1]);;
    :close(pipe[0]);;
  else (no)
  endif
  :execute the command;
  if (execution OK ?) then (success)
    stop
    note left
      Child process died
    end note
  else (fail)
    :print error execve;
    :exit (1);;
    stop
    note left
      Child process died
    end note
  endif
end fork

stop

@enduml
....
